name: Develop - Build and Deploy

on:
  push:
    branches: 
      - main 
    tags:
      - 'dev-v*.*.*'
env:
  VPS_WORKING_DIR: /srv/https/differential.com/evolution-api/8080:6379:5432:evolution-api

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy dist to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} 
          become: true  # Activa sudo
          # Selecting .yml"
          source: docker-compose.yaml
          # The path is based on the directory where the user logged into the server starts
          target: ${{ env.VPS_WORKING_DIR }}
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} 
          script: |
            cd ${{ env.VPS_WORKING_DIR }}
            ls -la
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker compose -f docker-compose.yaml pull
            docker compose -f docker-compose.yaml up -d --force-recreate
